In [6]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score


In [10]:
# Load the dataset
df = pd.read_csv("C://Users/anush/Desktop/ObesityDataSet_raw_and_data_sinthetic.csv")

# Display the first few rows
df.head()



Gender   Age  Height  Weight family_history_with_overweight FAVC  FCVC  \
0  Female  21.0    1.62    64.0                            yes   no   2.0   
1  Female  21.0    1.52    56.0                            yes   no   3.0   
2    Male  23.0    1.80    77.0                            yes   no   2.0   
3    Male  27.0    1.80    87.0                             no   no   3.0   
4    Male  22.0    1.78    89.8                             no   no   2.0   

   NCP       CAEC SMOKE  CH2O  SCC  FAF  TUE        CALC  \
0  3.0  Sometimes    no   2.0   no  0.0  1.0          no   
1  3.0  Sometimes   yes   3.0  yes  3.0  0.0   Sometimes   
2  3.0  Sometimes    no   2.0   no  2.0  1.0  Frequently   
3  3.0  Sometimes    no   2.0   no  2.0  0.0  Frequently   
4  1.0  Sometimes    no   2.0   no  0.0  0.0   Sometimes   

                  MTRANS           NObeyesdad  
0  Public_Transportation        Normal_Weight  
1  Public_Transportation        Normal_Weight  
2  Public_Transportation        Normal_Weight  
3                Walking   Overweight_Level_I  
4  Public_Transportation  Overweight_Level_II

In [17]:
# Define features and target variable
y = df['NObeyesdad']
X = df.drop('NObeyesdad', axis=1)
from sklearn.preprocessing import StandardScaler
# Convert categorical variables into numerical representations
X = pd.get_dummies(X, drop_first=True)

# Identify numerical columns
numerical_cols = X.select_dtypes(include=['float64', 'int64']).columns

# Standardize numerical features
scaler = StandardScaler()
X[numerical_cols] = scaler.fit_transform(X[numerical_cols])
from sklearn.model_selection import train_test_split
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [22]:

# Initialize the k-NN classifier with the desired number of neighbors (e.g., 5)
knn = KNeighborsClassifier(n_neighbors=5)

# Train the model
knn.fit(X_train_scaled, y_train)


KNeighborsClassifier()

In [24]:
# Predict the labels for the test set
y_pred = knn.predict(X_test_scaled)


In [26]:
# Print classification report
print("Classification Report:")
print(classification_report(y_test, y_pred))

# Print confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# Print accuracy score
print("Accuracy Score:")
print(accuracy_score(y_test, y_pred))


Classification Report:
                     precision    recall  f1-score   support

Insufficient_Weight       0.76      0.89      0.82        56
      Normal_Weight       0.67      0.53      0.59        62
     Obesity_Type_I       0.84      0.90      0.87        78
    Obesity_Type_II       0.90      0.97      0.93        58
   Obesity_Type_III       0.98      1.00      0.99        63
 Overweight_Level_I       0.74      0.71      0.73        56
Overweight_Level_II       0.80      0.72      0.76        50

           accuracy                           0.82       423
          macro avg       0.81      0.82      0.81       423
       weighted avg       0.82      0.82      0.82       423

Confusion Matrix:
[[50  3  0  0  0  3  0]
 [13 33  5  0  0  6  5]
 [ 0  2 70  2  0  2  2]
 [ 1  0  0 56  0  0  1]
 [ 0  0  0  0 63  0  0]
 [ 2  9  3  1  0 40  1]
 [ 0  2  5  3  1  3 36]]
Accuracy Score:
0.8226950354609929
